import streamlit as st

def render_renewable_percentage_info():
    """
    Renders comprehensive information about renewable percentage, the purpose of the page,
    and detailed information about Eco AI.ly's renewable percentage tracking features.
    """
    st.markdown("""
    # Renewable Percentage: Tracking the Clean Energy Revolution
    
    ## What is Renewable Percentage?
    
    Renewable percentage represents the proportion of total electricity generation that comes from renewable energy sources. It's a critical metric that measures how "green" your electricity is at any given moment, expressed as a percentage of total energy production.
    
    ### The Science Behind Renewable Energy
    
    Renewable energy comes from natural sources that are constantly replenished and produce little to no greenhouse gas emissions:
    
    - **Solar Power**: Energy from sunlight captured by photovoltaic panels or concentrated solar power systems
    - **Wind Energy**: Electricity generated by wind turbines that convert kinetic energy from wind into mechanical power
    - **Hydroelectric Power**: Energy produced from flowing water in rivers, dams, or ocean currents
    - **Biomass**: Energy from organic materials like wood, agricultural residues, and waste
    - **Geothermal Energy**: Heat extracted from the Earth's interior to generate electricity
    
    Unlike fossil fuels (coal, oil, natural gas), renewable energy sources:
    
    - Are naturally replenished on a human timescale
    - Produce minimal to zero greenhouse gas emissions during operation
    - Have lower environmental impacts in terms of air and water pollution
    - Create fewer health risks for nearby communities
    
    ### Renewable Percentage Classification
    
    Eco AI.ly classifies renewable percentage into six categories to help you quickly understand the environmental impact:
    
    1. **The Worst!** (< 16%): Very low renewable energy, primarily fossil fuel-based electricity
    2. **Very Bad!** (16-32%): Low renewable energy, significant reliance on fossil fuels
    3. **Bad!** (32-48%): Below average renewable energy, moderate fossil fuel dependence
    4. **Ok!** (48-64%): Average renewable energy, balanced energy mix
    5. **Good!** (64-80%): High renewable energy, primarily clean electricity
    6. **The Best!** (> 80%): Excellent renewable energy, almost entirely clean electricity
    
    ## Why Renewable Percentage Matters
    
    Understanding renewable percentage is crucial for several reasons:
    
    ### Environmental Impact
    
    - **Climate Change Mitigation**: Higher renewable percentages directly reduce greenhouse gas emissions
    - **Air Quality**: Cleaner energy sources lead to better air quality and reduced health impacts
    - **Biodiversity Protection**: Less habitat disruption compared to fossil fuel extraction
    - **Water Conservation**: Many renewable sources use significantly less water than thermal power plants
    
    ### Economic Benefits
    
    - **Energy Independence**: Reduced reliance on imported fossil fuels enhances energy security
    - **Job Creation**: The renewable energy sector creates more jobs per unit of energy than fossil fuels
    - **Price Stability**: Renewable energy can provide more stable electricity prices over time
    - **Economic Growth**: Investment in renewable energy stimulates local economies
    
    ### Policy and Planning
    
    - **Energy Transition Monitoring**: Tracks progress toward decarbonization goals
    - **Policy Effectiveness**: Helps evaluate the success of renewable energy incentives
    - **Infrastructure Planning**: Informs decisions about energy infrastructure investments
    - **International Commitments**: Measures progress toward international climate agreements
    
    ### Personal and Business Decision-Making
    
    - **Consumption Timing**: Enables informed choices about when to use electricity for minimal environmental impact
    - **Energy Efficiency**: Helps prioritize energy-saving measures during low renewable periods
    - **Renewable Energy Investment**: Guides decisions about installing solar panels or other renewable systems
    - **Corporate Sustainability**: Helps businesses reduce their carbon footprint and meet sustainability goals
    
    ## Eco AI.ly's Renewable Percentage Tools and Features
    
    ### 1. Real-Time Renewable Percentage Monitoring
    
    Our platform provides comprehensive time series data showing Portugal's renewable percentage trends in real-time:
    
    - **Interactive Visualization**: Zoom, pan, and explore renewable percentage patterns over the last 24 hours
    - **Detailed Metrics**: Current, average, minimum, maximum, and standard deviation values
    - **Trend Analysis**: Direction and strength of renewable percentage trends
    - **Time-Based Insights**: Identification of optimal times with highest renewable percentage
    
    This real-time monitoring allows you to:
    
    - Track daily, weekly, and monthly patterns
    - Identify peak renewable energy periods
    - Understand seasonal variations
    - Compare current values with historical data
    
    ### 2. AI-Powered Renewable Percentage Predictions
    
    Leveraging advanced machine learning models, we offer sophisticated prediction capabilities:
    
    - **24-Hour Forecasts**: Accurate predictions of renewable percentage for the next 24 hours
    - **Classification System**: Clear categorization of predicted renewable percentage (from "The Worst!" to "The Best!")
    - **Visual Indicators**: Color-coded displays (red to green) for intuitive understanding
    - **Consumption Recommendations**: Clear guidance on when to consume energy based on predictions
    
    Our prediction system:
    
    - Uses state-of-the-art LSTM (Long Short-Term Memory) neural networks
    - Incorporates multiple data sources including weather forecasts
    - Updates predictions continuously as new data becomes available
    - Provides confidence metrics to understand prediction reliability
    
    ### 3. Renewable Percentage Arbitrage Opportunities
    
    Our arbitrage tool helps you optimize your energy consumption timing:
    
    - **Energy Consumption Calculator**: Input your planned energy consumption to see potential environmental benefits
    - **Comparative Analysis**: Compare renewable percentages between current and future time periods
    - **Environmental Impact Quantification**: Calculate exact amounts of renewable energy that could be accessed by shifting consumption
    - **Actionable Recommendations**: Clear guidance on whether to consume energy now or later
    
    This feature is particularly valuable for:
    
    - Businesses with flexible energy consumption patterns
    - Electric vehicle charging optimization
    - Home appliance scheduling
    - Industrial processes that can be time-shifted
    
    ### 4. Comprehensive Renewable Percentage Reports
    
    Generate detailed PDF reports for documentation and sharing:
    
    - **Professional Formatting**: Clean, professional layout suitable for business presentations
    - **Data Visualization**: Includes charts and graphs of renewable percentage trends
    - **Detailed Metrics**: Comprehensive statistics and analysis
    - **Recommendations**: Actionable insights based on the data
    - **Exportable Format**: Easy to share with stakeholders, clients, or team members
    
    These reports are valuable for:
    
    - Corporate sustainability reporting
    - Environmental compliance documentation
    - Stakeholder communications
    - Internal decision-making processes
    
    ### 5. Model Performance Statistics
    
    For transparency and trust, we provide detailed statistics on our prediction models:
    
    - **Accuracy Metrics**: RMSE (Root Mean Square Error), MAE (Mean Absolute Error), R² (Coefficient of Determination)
    - **Training Methodology**: Insights into how our models are trained and validated
    - **Performance Visualizations**: Loss plots, accuracy plots, and confusion matrices
    - **Comparative Analysis**: How our models perform against baseline forecasting methods
    
    This transparency helps you:
    
    - Understand the reliability of our predictions
    - Make informed decisions based on model confidence
    - Trust the recommendations provided by our platform
    
    ## How to Use Renewable Percentage Data Effectively
    
    ### For Businesses
    
    - **Load Shifting**: Schedule energy-intensive operations during high renewable percentage periods
    - **Demand Response**: Participate in demand response programs that align with renewable energy patterns
    - **Sustainability Reporting**: Track and report on renewable energy consumption
    - **Energy Procurement**: Optimize energy purchasing strategies based on renewable percentage forecasts
    - **Facility Management**: Adjust building systems (HVAC, lighting) based on renewable percentage
    
    ### For Policymakers
    
    - **Policy Evaluation**: Assess the effectiveness of renewable energy incentives and carbon pricing
    - **Grid Planning**: Inform decisions about grid infrastructure and energy storage needs
    - **Renewable Targets**: Monitor progress toward national and international renewable energy targets
    - **Public Communication**: Provide transparent information about the environmental impact of electricity
    
    ### For Researchers
    
    - **Data Analysis**: Study correlations between renewable percentage and other environmental factors
    - **Model Development**: Use our data to develop and validate new forecasting models
    - **Impact Studies**: Assess the environmental impact of different energy policies
    - **Trend Analysis**: Identify long-term patterns in renewable percentage and their causes
    
    ### For Individuals
    
    - **Appliance Scheduling**: Run dishwashers, washing machines, and other appliances during high renewable periods
    - **EV Charging**: Optimize electric vehicle charging times for minimal environmental impact
    - **Home Energy Management**: Adjust thermostat settings and other home systems based on renewable percentage
    - **Environmental Awareness**: Develop a deeper understanding of your personal carbon footprint
    
    ## The Relationship Between Renewable Percentage and Carbon Intensity
    
    Renewable percentage and carbon intensity are closely related metrics that measure different aspects of the same phenomenon:
    
    - **Renewable Percentage**: Measures the proportion of clean energy in the mix (higher is better)
    - **Carbon Intensity**: Measures the amount of CO₂ emitted per unit of electricity (lower is better)
    
    Generally, as renewable percentage increases, carbon intensity decreases. This inverse relationship is why both metrics are valuable for:
    
    - Understanding the environmental impact of electricity
    - Making informed decisions about energy consumption
    - Tracking progress toward decarbonization goals
    
    Eco AI.ly provides both metrics to give you a complete picture of your electricity's environmental impact.
    
    ## The Future of Renewable Energy Tracking
    
    Eco AI.ly is continuously evolving to provide even more powerful renewable energy insights:
    
    - **Geographic Expansion**: Adding more countries and regions to our coverage
    - **Enhanced Predictions**: Improving forecast accuracy with more advanced AI models
    - **Integration Capabilities**: Developing APIs and integrations with other energy management systems
    - **Personalized Recommendations**: Creating customized suggestions based on user behavior patterns
    - **Renewable Energy Alerts**: Setting up notifications for optimal energy consumption times
    
    ## About Eco AI.ly
    
    Eco AI.ly is a pioneering environmental technology startup dedicated to making environmental data accessible and actionable. Our mission is to empower businesses, governments, and individuals with real-time environmental insights to drive sustainable decision-making and positive environmental impact.
    
    We combine cutting-edge artificial intelligence with comprehensive environmental data to provide accurate, timely, and actionable insights. Our platform is designed to be intuitive and informative, making complex environmental data understandable and useful for everyone.
    
    Currently focused on Portugal, we're rapidly expanding to provide similar insights for countries around the world, helping to drive global environmental awareness and action.
    
    ### Our Commitment to Accuracy
    
    All data presented on our platform is sourced from reliable, authoritative sources and processed using rigorous methodologies. Our AI models are regularly validated against actual renewable percentage measurements to ensure accuracy and reliability.
    
    ### Join Us in the Clean Energy Revolution
    
    By understanding and acting on renewable percentage data, you're taking an important step toward reducing greenhouse gas emissions and combating climate change. Together, we can accelerate the transition to a clean energy future for generations to come.
    """)

def main():
    render_renewable_percentage_info()

if __name__ == "__main__":
    main()
